services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:80
    depends_on:
      - front-end
      - server
      - server2
      - server3

  front-end:
    image: ghcr.io/mcmastercce/bvd-103-mcmasterful-books/mcmasterful-books-docker:main
    volumes:
      - ./adapter:/source/adapter
    expose:
      - "9080"
      
  server:
    image: node:20
    volumes:
      - ./:/app
    command: bash -c "chmod +x /app/start.sh && /app/start.sh"
    working_dir: /app
    expose:
      - "3000"
    depends_on:
      - mongo
      - mongo-warehouse
      - mongo-orders
      - rabbitmq
    environment:
      - NODE_ENV=production
      - PORT=3000
      - RABBITMQ_URL=amqp://admin:password@rabbitmq:5672
      - MONGO_BOOKS_URL=mongodb://mongo:27017/mcmasterful-books
      - MONGO_WAREHOUSE_URL=mongodb://mongo-warehouse:27017/mcmasterful-warehouse
      - MONGO_ORDERS_URL=mongodb://mongo-orders:27017/mcmasterful-orders

  server2:
    image: node:20
    volumes:
      - ./:/app
    command: bash -c "chmod +x /app/start.sh && /app/start.sh"
    working_dir: /app
    expose:
      - "3000"
    depends_on:
      - mongo
      - mongo-warehouse
      - mongo-orders
      - rabbitmq
    environment:
      - NODE_ENV=production
      - PORT=3000
      - RABBITMQ_URL=amqp://admin:password@rabbitmq:5672
      - MONGO_BOOKS_URL=mongodb://mongo:27017/mcmasterful-books
      - MONGO_WAREHOUSE_URL=mongodb://mongo-warehouse:27017/mcmasterful-warehouse
      - MONGO_ORDERS_URL=mongodb://mongo-orders:27017/mcmasterful-orders
    
  server3:
    image: node:20
    volumes:
      - ./:/app
    command: bash -c "chmod +x /app/start.sh && /app/start.sh"
    working_dir: /app
    expose:
      - "3000"
    depends_on:
      - mongo
      - mongo-warehouse
      - mongo-orders
      - rabbitmq
    environment:
      - NODE_ENV=production
      - PORT=3000
      - RABBITMQ_URL=amqp://admin:password@rabbitmq:5672
      - MONGO_BOOKS_URL=mongodb://mongo:27017/mcmasterful-books
      - MONGO_WAREHOUSE_URL=mongodb://mongo-warehouse:27017/mcmasterful-warehouse
      - MONGO_ORDERS_URL=mongodb://mongo-orders:27017/mcmasterful-orders

  mongo:
    image: mongo:latest
    expose:
      - "27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=mcmasterful-books

  mongo-warehouse:
    image: mongo:latest
    expose:
      - "27017"
    volumes:
      - mongo-warehouse-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=mcmasterful-warehouse

  mongo-orders:
    image: mongo:latest
    expose:
      - "27017"
    volumes:
      - mongo-orders-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=mcmasterful-orders

  rabbitmq:
    image: rabbitmq:3-management
    expose:
      - "5672"
      - "15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  mongo-data:
  mongo-warehouse-data:
  mongo-orders-data:
  rabbitmq-data: