services:
  nginx:
    depends_on:
      - books
      - orders
      - warehouse
      - front-end
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:80

  front-end:
    image: ghcr.io/mcmastercce/bvd-103-mcmasterful-books/mcmasterful-books-docker:main
    
    volumes:
      - ./adapter:/source/adapter

  books:
    depends_on:
      - mongo-books
      - rabbitmq
    image: node:22
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo-books:27017/books
      - RABBITMQ_URL=amqp://admin:password@rabbitmq:5672
    volumes:
      - ./books:/app
      - ./src:/app/src
      - ./node_modules:/app/node_modules
      - ./tsconfig.json:/app/tsconfig.json
      - ./documented_types.ts:/documented_types.ts
    command: npx -y tsx ./index.ts
    working_dir: /app

  orders:
    depends_on:
      - mongo-order
      - rabbitmq
    image: node:22
    volumes:
      - ./orders:/app
      - ./node_modules:/app/node_modules
      - ./tsconfig.json:/app/tsconfig.json
      - ./documented_types.ts:/documented_types.ts
    command: npx -y tsx ./index.ts
    working_dir: /app

  warehouse:
    depends_on:
      - mongo-warehouse
      - rabbitmq
    image: node:22
    volumes:
      - ./warehouse:/app
      - ./node_modules:/app/node_modules
      - ./tsconfig.json:/app/tsconfig.json
      - ./documented_types.ts:/documented_types.ts
    command: npx -y tsx ./index.ts
    working_dir: /app

  docs:
    image: node:22
    volumes:
      - ./docs:/app
      - ./node_modules:/app/node_modules
      - ./tsconfig.json:/app/tsconfig.json
      - ./build/swagger.json:/app/swagger.json
    command: npx -y tsx ./index.ts
    working_dir: /app

  mongo-books:
    image: mongo:latest
    ports:
      - "27017:27017"
  mongo-warehouse:
    image: mongo:latest
    ports:
      - "27019:27017"
  mongo-order:
    image: mongo:latest
    ports:
      - "27018:27017"

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password