# Development override file
# Use with: docker-compose -f docker-compose.yaml -f docker-compose.dev.yaml up

services:
  server:
    command: bash -c "chmod +x /app/start.sh && npm install && /app/start.sh"
    environment:
      - NODE_ENV=development
      - DEBUG=*
      - RABBITMQ_URL=amqp://admin:password@rabbitmq:5672
      - MONGO_BOOKS_URL=mongodb://mongo:27017/mcmasterful-books
      - MONGO_WAREHOUSE_URL=mongodb://mongo-warehouse:27017/mcmasterful-warehouse
      - MONGO_ORDERS_URL=mongodb://mongo-orders:27017/mcmasterful-orders
    volumes:
      - ./:/app
      - /app/node_modules

  server2:
    command: bash -c "chmod +x /app/start.sh && npm install && /app/start.sh"
    environment:
      - NODE_ENV=development
      - DEBUG=*
      - RABBITMQ_URL=amqp://admin:password@rabbitmq:5672
      - MONGO_BOOKS_URL=mongodb://mongo:27017/mcmasterful-books
      - MONGO_WAREHOUSE_URL=mongodb://mongo-warehouse:27017/mcmasterful-warehouse
      - MONGO_ORDERS_URL=mongodb://mongo-orders:27017/mcmasterful-orders
    volumes:
      - ./:/app
      - /app/node_modules

  server3:
    command: bash -c "chmod +x /app/start.sh && npm install && /app/start.sh"
    environment:
      - NODE_ENV=development
      - DEBUG=*
      - RABBITMQ_URL=amqp://admin:password@rabbitmq:5672
      - MONGO_BOOKS_URL=mongodb://mongo:27017/mcmasterful-books
      - MONGO_WAREHOUSE_URL=mongodb://mongo-warehouse:27017/mcmasterful-warehouse
      - MONGO_ORDERS_URL=mongodb://mongo-orders:27017/mcmasterful-orders
    volumes:
      - ./:/app
      - /app/node_modules

  mongo:
    ports:
      - "27017:27017"

  mongo-warehouse:
    ports:
      - "27018:27017"

  mongo-orders:
    ports:
      - "27019:27017"

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  nginx:
    # Enable nginx debug mode in development
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs:/var/log/nginx
